import openpyxl
import sys
sys.stdout.reconfigure(encoding='utf-8')

wb = openpyxl.load_workbook('docs/firefly_card_benchmark_template.xlsx')
ws = wb['design']

# 新增卡牌设计 - 基于 Ironclad 标准和流萤角色设定
new_cards = [
    # === 攻击卡补充 ===
    # Common 攻击 (需要补充8张，当前5张)
    ('ATT_COM_06', 'Attack', 'Common', 1, 'EnergyOverload', '能量超载',
     '获得2点能量。赋予自身2层灼热。升级：获得3点能量。',
     '灼热/能量', '透支未来'),
    ('ATT_COM_07', 'Attack', 'Common', 1, 'TimeDelayBurst', '偏时迸发',
     '本回合你的下一张攻击牌无视敌人格挡。升级：本回合所有攻击牌无视格挡。',
     '破甲', '无视防御'),
    ('ATT_COM_08', 'Attack', 'Common', 2, 'Breakthrough', '突破',
     '失去5点生命值。对所有敌人造成12点伤害。升级：造成18点伤害。',
     '自伤/AOE', '格拉默突击'),
    ('ATT_COM_09', 'Attack', 'Common', 1, 'GrappleStrike', '擒拿斩',
     '造成8点伤害。如果本回合造成过伤害，伤害+4。升级：伤害+6。',
     '连击', '萨姆近战'),
    ('ATT_COM_10', 'Attack', 'Common', 0, 'QuickStrike', '迅捷斩',
     '造成4点伤害。抽1张牌。升级：造成7点伤害。',
     '过牌', '快速攻击'),
    ('ATT_COM_11', 'Attack', 'Common', 2, 'HeavyBlow', '重击',
     '造成14点伤害。如果目标有灼热，伤害+6。升级：伤害+9。',
     '灼热/高伤', '灼热联动'),
    ('ATT_COM_12', 'Attack', 'Common', 2, 'ScorchingBlade', '灼热之刃',
     '造成6点伤害。施加3层灼热。升级：造成9点伤害，施加4层灼热。',
     '灼热', '灼热叠加'),
    ('ATT_COM_13', 'Attack', 'Common', 2, 'DissolutionWave', '裂解波动',
     '对所有敌人造成6点伤害。对所有有格挡的敌人赋予裂解。升级：造成9点伤害。',
     '裂解/AOE', '裂解体系'),

    # Uncommon 攻击 (需要补充11张，当前5张)
    ('ATT_UNC_06', 'Attack', 'Uncommon', 3, 'Devastator', '毁灭者',
     '造成26点伤害。升级：造成34点伤害。',
     '高伤', 'SAM重击'),
    ('ATT_UNC_07', 'Attack', 'Uncommon', 1, 'RisingFlame', '升腾之焰',
     '造成5点伤害。每层灼热使伤害+2。升级：每层灼热使伤害+3。',
     '灼热/成长', '灼热联动'),
    ('ATT_UNC_08', 'Attack', 'Uncommon', 2, 'FireflySwarm', '萤火群舞',
     '[萤火]造成5点伤害3次。激发：造成10点伤害3次，费用1。升级：造成7/14点伤害。',
     '萤火/连击', '萤火群攻'),
    ('ATT_UNC_09', 'Attack', 'Uncommon', 1, 'PrecisionStrike', '精准打击',
     '造成9点伤害。如果目标有裂解，抽1张牌。升级：抽2张牌。',
     '裂解/过牌', '裂解联动'),
    ('ATT_UNC_10', 'Attack', 'Uncommon', 2, 'EntropyBlade', '熵之刃',
     '造成10点伤害。移除目标所有格挡，每移除1点格挡造成2点伤害。升级：每点格挡造成3点伤害。',
     '裂解/格挡', '裂解体系'),
    ('ATT_UNC_11', 'Attack', 'Uncommon', 1, 'LifeBurning', '燃命',
     '失去等于当前能量值的生命值。造成等于失去生命值×2的伤害。升级：×3倍伤害。',
     '自伤/高伤', '生命燃烧'),
    ('ATT_UNC_12', 'Attack', 'Uncommon', 2, 'ScatterFlame', '散焰',
     '对所有敌人造成8点伤害。如果有敌人在灼热状态，额外施加2层灼热。升级：造成12点伤害。',
     '灼热/AOE', '灼热扩散'),
    ('ATT_UNC_13', 'Attack', 'Uncommon', 1, 'QuickDissolution', '快速裂解',
     '造成6点伤害。赋予目标裂解。如果目标已有裂解，改为造成12点伤害。升级：造成9/18点伤害。',
     '裂解', '裂解体系'),
    ('ATT_UNC_14', 'Attack', 'Uncommon', 2, 'FireflyNova', '萤火新星',
     '[萤火]对所有敌人造成7点伤害。激发：造成14点伤害，费用1。升级：造成10/20点伤害。',
     '萤火/AOE', '萤火爆发'),
    ('ATT_UNC_15', 'Attack', 'Uncommon', 1, 'RecklessCharge', '莽撞冲锋',
     '失去3点生命值。造成10点伤害。如果目标死于这张牌，回复3点生命值。升级：造成14点伤害。',
     '自伤', '格拉默冲锋'),

    # Rare 攻击 (需要补充5张，当前2张)
    ('ATT_RAR_03', 'Attack', 'Rare', 2, 'StarfireAnnihilation', '星火湮灭',
     '[萤火]造成25点伤害。激发：造成50点伤害，施加5层灼热，费用1。升级：造成33/66点伤害。',
     '萤火/爆发', '萤火终结技'),
    ('ATT_RAR_04', 'Attack', 'Rare', 3, 'OmegaBlaster', '欧米伽爆破',
     '消耗。对所有敌人造成20点伤害。施加5层灼热。升级：造成28点伤害，施加7层灼热。',
     '灼热/AOE', '消耗牌'),
    ('ATT_RAR_05', 'Attack', 'Rare', 1, 'FatalTrigger', '致命触发',
     '造成4点伤害。如果目标生命值低于25%，伤害变为3倍。升级：伤害变为4倍。',
     '收割', '斩杀'),
    ('ATT_RAR_06', 'Attack', 'Rare', 2, 'DissolutionAnnihilation', '裂解湮灭',
     '对所有拥有裂解的敌人造成15点伤害。每有一个裂解敌人，获得3点格挡。升级：造成21点伤害。',
     '裂解/AOE', '裂解收割'),
    ('ATT_RAR_07', 'Attack', 'Rare', 0, 'LastLight', '最后之光',
     '生命值低于10点时才能打出。对所有敌人造成等于当前生命值的伤害。升级：伤害+10。',
     '绝境/爆发', '萤火虫最后光芒'),

    # === 技能卡补充 ===
    # Common 技能 (需要补充4张，当前4张)
    ('SKI_COM_05', 'Skill', 'Common', 1, 'EnergyBoost', '能量激增',
     '获得1点能量。抽1张牌。升级：获得2点能量。',
     '能量/过牌', '快速充能'),
    ('SKI_COM_06', 'Skill', 'Common', 2, 'ReinforcedArmor', '强化装甲',
     '获得12点格挡。如果你的生命值低于50%，额外获得6点格挡。升级：获得16点格挡。',
     '格挡/生存', 'SAM装甲'),
    ('SKI_COM_07', 'Skill', 'Common', 0, 'DesperateDefense', '绝境防御',
     '获得5点格挡。生命值每低于最大值10点，格挡+2。升级：格挡+3。',
     '格挡/生存', '低血量加成'),
    ('SKI_COM_08', 'Skill', 'Common', 1, 'EmergencyRepair', '紧急修复',
     '失去2点生命值。获得8点格挡。抽1张牌。升级：获得12点格挡。',
     '自伤/格挡', '快速修复'),

    # Uncommon 技能 (需要补充9张，当前3张)
    ('SKI_UNC_04', 'Skill', 'Uncommon', 1, 'FireflyDance', '萤火之舞',
     '抽2张牌。本回合你打出的下一张攻击牌费用为0。升级：抽3张牌。',
     '过牌/减费', '快速连击'),
    ('SKI_UNC_05', 'Skill', 'Uncommon', 1, 'ScorchAbsorb', '灼热吸收',
     '移除一个敌人身上的所有灼热。每移除1层，回复2点生命值。升级：回复3点生命值。',
     '灼热/回复', '灼热转化'),
    ('SKI_UNC_06', 'Skill', 'Uncommon', 2, 'BarrierTransfer', '屏障转移',
     '将目标敌人身上的所有格挡转移给自己。升级：转移的格挡+50%。',
     '裂解/格挡', '裂解体系'),
    ('SKI_UNC_07', 'Skill', 'Uncommon', 0, 'FireflySpark', '萤火迸发',
     '[萤火]激发手牌中一张萤火牌。升级：激发所有萤火牌。',
     '萤火/激发', '萤火辅助'),
    ('SKI_UNC_08', 'Skill', 'Uncommon', 1, 'TacticalRetreat', '战术撤退',
     '获得6点格挡。将手牌中所有萤火牌置入弃牌堆，每张抽1张牌。升级：获得9点格挡。',
     '萤火/过牌', '萤火循环'),
    ('SKI_UNC_09', 'Skill', 'Uncommon', 2, 'DissolutionField', '裂解力场',
     '对所有敌人赋予裂解。获得等于敌人数量×3的格挡。升级：获得×5的格挡。',
     '裂解/防御', '裂解体系'),
    ('SKI_UNC_10', 'Skill', 'Uncommon', 1, 'BurningSpirit', '燃烧意志',
     '失去4点生命值。本回合获得2层力量。升级：获得3层力量。',
     '自伤/力量', '燃烧增益'),
    ('SKI_UNC_11', 'Skill', 'Uncommon', 2, 'EntropyShield', '熵之盾',
     '获得等于当前失去生命值一半的格挡。升级：获得等于失去生命值的格挡。',
     '格挡/生存', '低血量加成'),
    ('SKI_UNC_12', 'Skill', 'Uncommon', 1, 'QuickIgnition', '快速点燃',
     '选择手牌中一张牌，使其获得萤火属性。抽1张牌。升级：抽2张牌。',
     '萤火/过牌', '萤火赋予'),

    # Rare 技能 (需要补充5张，当前3张)
    ('SKI_RAR_04', 'Skill', 'Rare', 1, 'LifeWhySleep', '生命因何而沉睡',
     '生命值上限减少10点。本场战斗获得3点能量。升级：减少8点，获得4点能量。',
     '风险/能量', '哲学命题'),
    ('SKI_RAR_05', 'Skill', 'Rare', 2, 'FireflyCycle', '萤火循环',
     '将弃牌堆中所有萤火牌返回手牌。获得等于返回数量×2的格挡。升级：获得×3格挡。',
     '萤火/循环', '萤火回收'),
    ('SKI_RAR_06', 'Skill', 'Rare', 1, 'TimeStop', '时停',
     '本回合敌人不行动。你受到的所有伤害+5。消耗。升级：受到伤害+3。',
     '控制/风险', '时间停止'),
    ('SKI_RAR_07', 'Skill', 'Rare', 0, 'OmeletCake', '橡木蛋糕卷',
     '回复15点生命值。获得1点能量。每场战斗限用1次。升级：回复20点生命值，获得2点能量。',
     '回复/能量', '流萤最爱'),
    ('SKI_RAR_08', 'Skill', 'Rare', 1, 'RooftopPhoto', '天台合影',
     '获得8点格挡。抽1张牌。如果手牌中有萤火牌，额外获得4点格挡。升级：获得12点格挡，抽2张牌。',
     '格挡/过牌', '美好回忆'),

    # === 能力卡补充 ===
    # Uncommon 能力 (需要补充9张，当前2张)
    ('POW_UNC_03', 'Power', 'Uncommon', 1, 'ThermalReaction', '热核反应',
     '每当你施加灼热，获得1点格挡。升级：获得2点格挡。',
     '灼热/格挡', '灼热联动'),
    ('POW_UNC_04', 'Power', 'Uncommon', 2, 'BurningWill', '燃烧意志',
     '生命值低于50%时，伤害+2。升级：伤害+3。',
     '自伤/力量', '低血量增益'),
    ('POW_UNC_05', 'Power', 'Uncommon', 1, 'FireflyResonance', '萤火共鸣',
     '萤火牌激发时，额外获得1点能量。升级：获得2点能量。',
     '萤火/能量', '萤火增益'),
    ('POW_UNC_06', 'Power', 'Uncommon', 1, 'BlockMastery', '格挡精通',
     '从卡牌获得的格挡+3。升级：格挡+5。',
     '格挡', '防御强化'),
    ('POW_UNC_07', 'Power', 'Uncommon', 2, 'ScorchMastery', '灼热精通',
     '施加的灼热层数+1。升级：灼热层数+2。',
     '灼热', '灼热强化'),
    ('POW_UNC_08', 'Power', 'Uncommon', 1, 'DissolutionResonance', '裂解共鸣',
     '触发裂解伤害时，额外造成等于伤害值20%的伤害。升级：30%额外伤害。',
     '裂解', '裂解强化'),
    ('POW_UNC_09', 'Power', 'Uncommon', 2, 'LifeExchange', '生命交换',
     '回合开始时，失去2点生命值，获得1层力量。升级：失去1点生命值。',
     '自伤/力量', '生命转化'),
    ('POW_UNC_10', 'Power', 'Uncommon', 1, 'FireflyMemory', '萤火记忆',
     '萤火牌被打出后，有50%概率返回手牌。升级：75%概率。',
     '萤火/循环', '萤火回收'),
    ('POW_UNC_11', 'Power', 'Uncommon', 2, 'ArmorBreaker', '破甲专家',
     '你造成的伤害对格挡额外造成50%伤害。升级：额外造成100%伤害。',
     '裂解/破甲', '裂解体系'),

    # Rare 能力 (需要补充9张，当前3张)
    ('POW_RAR_04', 'Power', 'Rare', 2, 'ThreeDeaths', '三次死亡',
     '本场战斗限3次：当你生命值降至1时，获得无敌1回合并抽2张牌。升级：获得无敌2回合。',
     '生存/复活', '流萤命运'),
    ('POW_RAR_05', 'Power', 'Rare', 2, 'FireflyNest', '萤火之巢',
     '回合结束时，将手牌中一张随机非萤火牌变为萤火牌。升级：变2张。',
     '萤火/转化', '萤火生成'),
    ('POW_RAR_06', 'Power', 'Rare', 3, 'Inferno', '地狱火',
     '灼热触发时，有50%概率不减少层数。升级：75%概率。',
     '灼热/持续', '灼热增强'),
    ('POW_RAR_07', 'Power', 'Rare', 2, 'EntropyMaster', '熵之主宰',
     '每当你赋予裂解，获得1点能量。升级：获得2点能量。',
     '裂解/能量', '裂解体系'),
    ('POW_RAR_08', 'Power', 'Rare', 1, 'LastStand', '背水一战',
     '生命值低于20点时，攻击牌耗能-1。升级：生命值低于25点时生效。',
     '自伤/减费', '低血量增益'),
    ('POW_RAR_09', 'Power', 'Rare', 2, 'FireflyBlessing', '萤火祝福',
     '萤火牌激发时效果额外+50%。升级：效果+100%。',
     '萤火/增强', '萤火核心'),
    ('POW_RAR_10', 'Power', 'Rare', 3, 'PhoenixRise', '凤凰涅槃',
     '本场战斗第一次死亡时，以50%生命值复活，激发所有手牌中的萤火牌。升级：以75%生命值复活。',
     '生存/复活', '重生'),
    ('POW_RAR_11', 'Power', 'Rare', 1, 'ScorchAura', '灼热光环',
     '回合开始时，对有灼热的敌人造成等同于灼热层数50%的伤害。升级：造成75%伤害。',
     '灼热', '灼热增强'),
    ('POW_RAR_12', 'Power', 'Rare', 2, 'DissolutionCore', '裂解核心',
     '裂解伤害翻倍。升级：裂解伤害×3。',
     '裂解', '裂解核心'),
]

# 添加新卡牌到设计表
for card in new_cards:
    ws.append(card)

wb.save('docs/firefly_card_benchmark_template.xlsx')
print(f"已添加 {len(new_cards)} 张新卡牌设计")
